create table if not exists public.content (
  id bigint generated by default as identity primary key,
  page text not null,
  key text not null,
  value text not null,
  updated_at timestamptz not null default now(),
  constraint content_page_key_unique unique (page, key)
);

create index if not exists content_page_idx on public.content (page);
create index if not exists content_updated_at_idx on public.content (updated_at desc);